runtime: nodejs18

# App Engine Standard Environment configuration
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Environment variables (non-sensitive only)
env_variables:
  NODE_ENV: 'production'
  PORT: '8080'

# Health check configuration
liveness_check:
  path: '/health'
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: '/health'
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# VPC configuration (if using VPC connector)
# vpc_access_connector:
#   name: 'projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME'
