# Google Cloud Build configuration for CI/CD
# This file automates the build and deployment process to GCP

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bezhas-web3:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bezhas-web3:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bezhas-web3:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/bezhas-web3:latest'
    id: 'push-latest'
    waitFor: ['push-image']

  # Step 4: Deploy to Cloud Run (Option 1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bezhas-web3'
      - '--image=gcr.io/$PROJECT_ID/bezhas-web3:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=MONGODB_URI=MONGODB_URI:latest,PRIVATE_KEY=PRIVATE_KEY:latest,JWT_SECRET=JWT_SECRET:latest'
    id: 'deploy-cloudrun'
    waitFor: ['push-latest']

  # Step 5: Deploy to GKE (Option 2 - Uncomment if using Kubernetes)
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args:
  #     - 'set'
  #     - 'image'
  #     - 'deployment/bezhas-web3'
  #     - 'bezhas-web3=gcr.io/$PROJECT_ID/bezhas-web3:$COMMIT_SHA'
  #   env:
  #     - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=bezhas-cluster'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/bezhas-web3:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/bezhas-web3:latest'

# Build configuration options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for the entire build
timeout: '1200s'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'bezhas-web3'
