# ===================================================
# BeZhas Backend - App Engine Configuration
# ===================================================
# Deploy with: gcloud app deploy backend/app.yaml
# ===================================================

runtime: nodejs20
service: default

# Instance configuration
instance_class: F2

# Auto-scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 80

# Environment variables
env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  LOG_LEVEL: "info"
  ALLOWED_ORIGINS: "https://bezhas.com,https://www.bezhas.com,https://bezhas-frontend-371791663100.us-central1.run.app,https://totemic-bonus-479312-c6.ew.r.appspot.com"

# Build configuration
build_env_variables:
  NODE_ENV: "production"

# Entry point
entrypoint: node server.js

# VPC connector for private network access (optional)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/us-central1/connectors/bezhas-connector
#   egress_setting: all-traffic

# Health checks
liveness_check:
  path: "/api/health/live"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2
  initial_delay_sec: 30

readiness_check:
  path: "/api/health/ready"
  check_interval_sec: 10
  timeout_sec: 5
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 300

# Network settings
network:
  session_affinity: true

# Handlers
handlers:
  - url: /api/.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always

# Includes
includes:
  - app-secrets.yaml # Create this file with secret references
